version: "3.9"
services:
  dns:
    image: ubuntu/bind9:9.18-22.04_beta
    environment:
      - TZ=Europe/Warsaw
      - BIND9_USER=root
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns/config:/etc/bind
      - ./dns/cache:/var/cache/bind
      - ./dns/records:/var/lib/bind
    restart: unless-stopped
  reverse-proxy:
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./prometheus/data:/prometheus
    restart: always
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/dashboards/home.json:/usr/share/grafana/public/dashboards/home.json
    depends_on:
      - prometheus
    restart: always
  unpoller:
    image: golift/unifi-poller:latest
    ports:
      - "9130:9130"
    depends_on:
      - prometheus
    volumes:
      - ./unpoller:/config
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"
  boiler-exporter:
    build: ./boiler-exporter/src
    environment:
      - EMS_ESP_IP=192.168.10.56
    expose:
      - 80
    ports:
      - "9080:80"
