version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./prometheus/data:/prometheus
    restart: always
    labels:
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.sopranowa.pl`)"
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/dashboards/home.json:/usr/share/grafana/public/dashboards/home.json
    depends_on:
      - prometheus
    restart: always
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.sopranowa.pl`)"
  unpoller:
    image: golift/unifi-poller:latest
    ports:
      - "9130:9130"
    depends_on:
      - prometheus
    volumes:
      - ./unpoller:/config
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
#    ports:
#      - "1883:1883"
#      - "9001:9001"
    restart: unless-stopped
    labels:
      - "traefik.tcp.services.mqtt.loadbalancer.server.port=1883"
      - "traefik.tcp.services.mqtt_websocket.loadbalancer.server.port=9001"
      - "traefik.tcp.routers.mosquitto.entrypoints=mqtt"
      - "traefik.tcp.routers.mosquitto.rule=Host(`mqtt.sopranowa.pl`)"
      - "traefik.tcp.routers.mosquitto.service=mqtt"
      - "traefik.tcp.routers.mosquitto_websocket.entrypoints=mqtt_websocket"
      - "traefik.tcp.routers.mosquitto_websocket.rule=Host(`mqtt.sopranowa.pl`)"
      - "traefik.tcp.routers.mosquitto_websocket.service=mqtt_websocket"
  boiler-exporter:
    build: ./boiler-exporter/src
    environment:
      - EMS_ESP_IP=192.168.10.56
    expose:
      - 80
    ports:
      - "9080:80"
    labels:
      - "traefik.http.routers.boiler-exporter.rule=Host(`boiler.sopranowa.pl`)"
    restart: unless-stopped
