version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./prometheus/data:/prometheus
    restart: always
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/dashboards/home.json:/usr/share/grafana/public/dashboards/home.json
    depends_on:
      - prometheus
    restart: always
  unpoller:
    image: golift/unifi-poller:latest
    ports:
      - "9130:9130"
    depends_on:
      - prometheus
    volumes:
      - ./unpoller:/config
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"