version: "3.9"
services:
  reverse-proxy:
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./prometheus/data:/prometheus
    restart: always
    labels:
      - "traefik.http.routers.my-container.rule=Host(`prometheus.sopranowa.pl`)"
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/dashboards/home.json:/usr/share/grafana/public/dashboards/home.json
    depends_on:
      - prometheus
    restart: always
    labels:
      - "traefik.http.routers.my-container.rule=Host(`grafana.sopranowa.pl`)"
  unpoller:
    image: golift/unifi-poller:latest
    ports:
      - "9130:9130"
    depends_on:
      - prometheus
    volumes:
      - ./unpoller:/config
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
    ports:
      - "1883:1883"
      - "9001:9001"
  boiler-exporter:
    build: ./boiler-exporter/src
    environment:
      - EMS_ESP_IP=192.168.10.56
    expose:
      - 80
    ports:
      - "9080:80"
    labels:
      - "traefik.http.routers.my-container.rule=Host(`boiler.sopranowa.pl`)"
