{
 "title": "Home",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "SALON",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "temp{room=\"salon\"}",
     "legendFormat": "TEMP"
    },
    {
     "expr": "target_temp{room=\"salon\"}",
     "legendFormat": "TARGET"
    }
   ]
  },
  {
   "title": "SYPIALNIE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "temp{room=\"sypialnia_n\"}",
     "legendFormat": "TEMP SYPIALNIA N"
    },
    {
     "expr": "temp{room=\"sypialnia_w\"}",
     "legendFormat": "TEMP SYPIALNIA W"
    },
    {
     "expr": "temp{room=\"sypialnia_s\"}",
     "legendFormat": "TEMP SYPIALNIA S"
    },
    {
     "expr": "target_temp{room=\"sypialnie\"}",
     "legendFormat": "TARGET"
    }
   ]
  },
  {
   "title": "ŁAZIENKI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "temp{room=\"lazienka_mala\"}",
     "legendFormat": "TEMP"
    },
    {
     "expr": "target_temp{room=\"lazienka_mala\"}",
     "legendFormat": "TARGET"
    }
   ]
  },
  {
   "title": "KINO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "temp{room=\"kino\"}",
     "legendFormat": "TEMP"
    },
    {
     "expr": "target_temp{room=\"kino\"}",
     "legendFormat": "TARGET"
    }
   ]
  },
  {
   "title": "WIATROŁAP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "temp{room=\"wiatrolap\"}",
     "legendFormat": "TEMP"
    },
    {
     "expr": "target_temp{room=\"wiatrolap\"}",
     "legendFormat": "TARGET"
    }
   ]
  },
  {
   "title": "GARAŻ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "temp{room=\"garaz\"}",
     "legendFormat": "TEMP"
    }
   ]
  },
  {
   "title": "ZAWORY",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "valve{room=\"salon\"}",
     "legendFormat": "SALON"
    },
    {
     "expr": "valve{room=\"sypialnie\"}",
     "legendFormat": "SYPIALNIE"
    },
    {
     "expr": "valve{room=\"lazienka_mala\"}",
     "legendFormat": "LAZIENKA MALA"
    },
    {
     "expr": "valve{room=\"wiatrolap\"}",
     "legendFormat": "WIATROLAP"
    }
   ]
  },
  {
   "title": "OUTSIDE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "temp{room=\"outside\"}    ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}