version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "traefik.http.routers.portainer.rule=Host(`portainer.sopranowa.pl`)"
      - "traefik.http.services.portainer-portainer.loadbalancer.server.port=9000"
    network_mode: host
volumes:
  portainer_data:
    name: portainer_data
    external: true